name: frontend
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  equatable: ^1.2.0
  meta: ^1.1.8
  uuid: ^2.1.0
  formz: ^0.2.0

  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.0.3
  mockito: ^4.1.1

flutter:
  uses-material-design: true
